### ISSUE TITLE
To Be Fair...

### ISSUE THREAD

**Issue by amadeus** [billyvg/tigris.nvim#9]
Your screenshot comparing to vim-javascript is pretty misleading. We actually apply matchgroups to many areas that your color scheme isn't applying too. 😛 

![example](https://dl.dropboxusercontent.com/s/psdmrr34ewnnkua/Developmentdiscorddiscord_app_2017-01-25_15-40-59.png?dl=0)

However, I will admit, our flow highlighting needs a lot of work still 😞

**Comment by billyvg** [comment]
Ah, you're definitely right - it was my colorscheme that's lacking a bit.

This project was mostly for educational purposes, i.e. to play around with node plugins in neovim, and also solve some pain points from flow (which have been fixed in vim-javascript since). It also doesn't seem very practical to continuously run through an AST parser, especially on large files.

**Comment by amadeus** [comment]
Yeah no worries at all! I think an idea like this, built into an editor could actually be a fantastic system though, and would put us syntax file writers out of a job! (a good thing!)
